name: CI & CD
on:
  workflow_dispatch:

env:
  WORKDIR: "/home/mappingsiteadmin/project"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Stop Pgadmin & Postgres containers
        uses: cross-the-world/ssh-pipeline@master
        with:
          host: ${{ secrets.DC_HOST }}
          user: ${{ secrets.DC_USER }}
          pass: ${{ secrets.DC_PASS }}
          port: ${{ secrets.DC_PORT }}
          connect_timeout: 10s
          script: |
            cd $WORKDIR/MappingSite
            sudo docker-compose down
            
      - name: Remove old packages
        uses: cross-the-world/ssh-pipeline@master
        with:
          host: ${{ secrets.DC_HOST }}
          user: ${{ secrets.DC_USER }}
          pass: ${{ secrets.DC_PASS }}
          port: ${{ secrets.DC_PORT }}
          connect_timeout: 10s
          script: |
            cd $WORKDIR
            rm -rf *
            
      - name: Clone new packages
        env:
          TOKEN: ${{ secrets.DC_TOKEN }}
        uses: cross-the-world/ssh-pipeline@master
        with:
          host: ${{ secrets.DC_HOST }}
          user: ${{ secrets.DC_USER }}
          pass: ${{ secrets.DC_PASS }}
          port: ${{ secrets.DC_PORT }}
          connect_timeout: 10s
          script: |
            cd $WORKDIR
            git clone https://phy0sithukyaw:$TOKEN@github.com/SaiHormKham-BlissStock/MappingSite.git
            
      - name: Build Run on Server
        uses: cross-the-world/ssh-pipeline@master
        with:
          host: ${{ secrets.DC_HOST }}
          user: ${{ secrets.DC_USER }}
          pass: ${{ secrets.DC_PASS }}
          port: ${{ secrets.DC_PORT }}
          connect_timeout: 10s
          script: |
            cd $WORKDIR/MappingSite
            ./gradlew build
            
      - name: Start Pgadmin & Postgres containers
        uses: cross-the-world/ssh-pipeline@master
        with:
          host: ${{ secrets.DC_HOST }}
          user: ${{ secrets.DC_USER }}
          pass: ${{ secrets.DC_PASS }}
          port: ${{ secrets.DC_PORT }}
          connect_timeout: 10s
          script: |
            cd $WORKDIR/MappingSite
            sudo docker-compose up -d
            
